### ISSUE TITLE
RFE: Use dynamic subdomain URL 

### ISSUE THREAD

**Issue by tqvarnst** [redhat-helloworld-msa/frontend#2]
The OpenShift application subdomain is hardcoded in the frontend code to *.rhel-cdk.10.1.2.2.xip.io" in: 
- Index.html,
- scripts/api-gateway.js,
- scripts/browser-client.js
- scripts/service-chain.js. 

It would be nice if the OpenShift URL could be dynamically set using environment variables instead of of hardcoded.

**Comment by burrsutter** [comment]
At a minimum, we should place all of these URLs into their own .js file that defines the URLs.  A second step would be then to figure out how adjust that single .js file based on the "bring up" (installation, configuration) of a non-CDK OpenShift.

**Comment by rafabene** [comment]
I just commited a version that contains all urls in a single file hosted in the server-side: https://github.com/redhat-helloworld-msa/frontend/blob/master/services.json This can be a principle of a service-registry.

**Comment by rafabene** [comment]
@tqvarnst . Thanks to @dustymabe's  contribution, you can now overwrite the OS_SUBDOMAIN and OS_PROJECT env vars to customize it according to your needs. Thanks
